### ISSUE TITLE
Historia de usuario 1 - Garçom/Garçonete deve poder entrar no sistema, caso o admin já lhe tenha dado as credenciais

### ISSUE THREAD

**Issue by NiEl0503** [NiEl0503/BurgerBots#4]
- [x] Eu, como garçom/garçonete quero entrar no sistema de pedidos.

**Critérios de aceitação**
O que deve acontecer para satisfazer as necessidades do usuário?

 - [x] Acessar uma tela de login.
- [x]  Inserir email e senha.
 - [x] Receber mensagens de erros compreensíveis, conforme o erro e as informações inseridas.
 - [x] Entrar no sistema de pedidos caso as credenciais forem corretas.
 
**Definição de pronto**
O acordado abaixo deve acontecer para dizer que a história está terminada:

- [x]  Você deve ter recebido code review de pelo menos uma parceira.
 - [x] Fez testes unitários e, além disso, testou seu produto manualmente.
 - [x] Você fez testes de usabilidade e incorporou o feedback do usuário.
 - [x] Você deu deploy de seu aplicativo e marcou sua versão (tag git).

**Comment by carolprotasio** [comment]
[História de usuário 2] Garçom/Garçonete deve ser capaz de anotar o pedido do cliente
Eu como garçom/garçonete quero poder anotar o pedido de um cliente para não depender da minha memória, saber quanto cobrar e poder enviar os pedidos para a cozinha para serem preparados em ordem.

Critérios de aceitação
O que deve acontecer para satisfazer as necessidades do usuário?

Anotar o nome do cliente.
Adicionar produtos aos pedidos.
Excluir produtos.
Ver resumo e o total da compra.
Enviar o pedido para a cozinha (guardar em algum banco de dados).
Funcionar bem em um tablet.
Definição de pronto
O acordado abaixo deve acontecer para dizer que a história está terminada:

Você deve ter recebido code review de pelo menos uma parceira.
Fez testes unitários e, além disso, testou seu produto manualmente.
Você fez testes de usabilidade e incorporou o feedback do usuário.
Você deu deploy de seu aplicativo e marcou sua versão (tag git).

**Comment by NiEl0503** [comment]
![Image](https://github.com/NiEl0503/BurgerBots/assets/125376144/02591d2a-ac59-4cc7-a32d-ddc4cb3a6fb9)
